select * from customers;
--Q1. What is the total revenue generated by male vs. female customers?
 select gender,SUM(purchase_amount) aS revenue
from customers 
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id , purchase_amount
from customers
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customers)

--Q3. Which are the top 5 products with the highest average review rating?
select top 5 
    item_purchased,
    ROUND(AVG(CAST(review_rating as FLOAT)), 2) as [Average Product Rating]
from customers
group by item_purchased
order by AVG(CAST(review_rating as FLOAT)) DESC;

--Q4. Compare the average purchase amounts between Standard and Express Shipping.
select shipping_type,
AVG(purchase_amount)
from customers
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customers
group by subscription_status
order by total_revenue, avg_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 
    item_purchased,
    ROUND(
        (SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END) * 100.0) 
        / COUNT(*), 
        2
    ) AS discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate DESC;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id,previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'NEW'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customers
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category?
with item_counts as (
    select
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            order by COUNT(*) DESC
        ) AS rn
    from customers
    group by category, item_purchased
)

select 
    category,
    item_purchased,
    total_purchases
from item_counts
where rn <= 3
order by category, total_purchases DESC;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe
select subscription_status,
COUNT(customer_id) as repeat_buyers
from customers
where previous_purchases >5
group by subscription_status;


--Q10. What is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customers
group by age_group
order by total_revenue DESC;

